### ISSUE TITLE
Answer Boxes Should Have Cursor: Hover Styling

### ISSUE THREAD

**Issue by SimonPringleWallace** [mickey-vershbow/mickey-vershbow.github.io#1]
Any clickable element in the app, such as buttons, question answers, etc. should have a `cursor: hover` style. 

Steps to reproduce:
1. Load the app
2. Hover the mouse over one of the answer boxes

Expect - Mouse assumes a hover styling
Actual - Mouse has default styling in the container for the button and then a text styling when hovering over the text

**Comment by mickey-vershbow** [comment]
Brilliant. Done, thanks!
